server:
  port: 8080

application:
  version: 1.0

spring:
  application.name: lunch-voter

  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:file:./data/db
    driverClassName: org.h2.Driver
    username: sa
    password: 123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database-platform: org.hibernate.dialect.H2Dialect


  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER